/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:45a12068-0c6c-44f2-b903-d97b4890319e",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_z4mOdRMS1",
    "aws_user_pools_web_client_id": "5cvo7ld3g1p67k7no80su2a57i",
    "oauth": {}
};


export default awsmobile;
